POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im15bXkiLCJpZCI6IjVjNmZkMWUwYzVjMjhlMDQ3MmJmMGM5YyIsImlhdCI6MTU1MDgzNTY3NX0.iHZBm4gDL81DwXUWJ6xCtKlsVOhLwhcZVu71I0NzRtA

{
        "title": "React patterns",
        "author": "Michael Chan",
        "url": "https://reactpatterns.com/",
        "likes": 7,
        "userId": "5c6fd1e0c5c28e0472bf0c9c"
}