POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhcmltYXJpIiwiaWQiOiI1YzZlOGUwOWU1ZTZlZTA2MzdlYTRjNDMiLCJpYXQiOjE1NTA3NDkxOTh9.VH7kP56VCh_dG5It0GeBx0JihRE9PuxL0EPdUvXE4W8

{
        "title": "Opi jo",
        "author": "Mina",
        "url": "joku fiksu paikka",
        "likes": 2,
        "userId": "5c6e7b46da9f1a02a3f844c8"
}